In [1]:
import pandas as pd
import numpy as np

In [2]:
stock=pd.read_csv("../data/reliance_stock_data.csv")

In [3]:
stock.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2014-01-01,187.46730041503906,189.46051090656061,187.2141873927095,189.2917641983991,5849398
3,2014-01-02,184.5565643310547,188.98592221291577,183.5230488999362,187.23526500521035,6023632
4,2014-01-03,182.2891387939453,184.2085285056438,180.3381117186358,183.8394118503579,12833897

In [4]:
stock.shape

(2712, 6)

In [5]:
stock.dtypes

Price     str
Close     str
High      str
Low       str
Open      str
Volume    str
dtype: object

In [6]:
stock.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [7]:
import yfinance as yf

stock = yf.download(
    "RELIANCE.NS",
    start="2014-01-01",
    end="2024-12-31"
)

[*********************100%***********************]  1 of 1 completed

In [8]:
stock.head()

Price            Close        High         Low        Open      Volume
Ticker     RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS
Date
2014-01-01  187.467316  189.460526  187.214203  189.291780     5849398
2014-01-02  184.556564  188.985922  183.523049  187.235265     6023632
2014-01-03  182.289169  184.208559  180.338142  183.839443    12833897
2014-01-06  180.327576  182.078233  179.283514  181.835666    13315857
2014-01-07  177.617279  181.382225  177.184888  180.253797    17311470

In [9]:
stock.columns = stock.columns.get_level_values(0)

In [10]:
stock.head()

Price            Close        High         Low        Open    Volume
Date
2014-01-01  187.467316  189.460526  187.214203  189.291780   5849398
2014-01-02  184.556564  188.985922  183.523049  187.235265   6023632
2014-01-03  182.289169  184.208559  180.338142  183.839443  12833897
2014-01-06  180.327576  182.078233  179.283514  181.835666  13315857
2014-01-07  177.617279  181.382225  177.184888  180.253797  17311470

In [11]:
stock.columns = stock.columns.get_level_values(0)

In [12]:
stock.head()

Price            Close        High         Low        Open    Volume
Date
2014-01-01  187.467316  189.460526  187.214203  189.291780   5849398
2014-01-02  184.556564  188.985922  183.523049  187.235265   6023632
2014-01-03  182.289169  184.208559  180.338142  183.839443  12833897
2014-01-06  180.327576  182.078233  179.283514  181.835666  13315857
2014-01-07  177.617279  181.382225  177.184888  180.253797  17311470

In [13]:
stock.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2710 entries, 2014-01-01 to 2024-12-30
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   2710 non-null   float64
 1   High    2710 non-null   float64
 2   Low     2710 non-null   float64
 3   Open    2710 non-null   float64
 4   Volume  2710 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 127.0 KB

In [14]:
stock.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-06',
               '2014-01-07', '2014-01-08', '2014-01-09', '2014-01-10',
               '2014-01-13', '2014-01-14',
               ...
               '2024-12-16', '2024-12-17', '2024-12-18', '2024-12-19',
               '2024-12-20', '2024-12-23', '2024-12-24', '2024-12-26',
               '2024-12-27', '2024-12-30'],
              dtype='datetime64[s]', name='Date', length=2710, freq=None)

In [15]:
stock.index.dtype

dtype('<M8[s]')

In [16]:
stock.isnull().sum()

Price
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [17]:
stock.duplicated().sum()

np.int64(0)

In [18]:
stock.sort_index(inplace=True)

In [19]:
stock.tail()

Price             Close         High          Low         Open    Volume
Date
2024-12-23  1211.834717  1216.692666  1202.812534  1204.597171  10052824
2024-12-24  1212.280762  1222.988340  1210.545745  1211.834663   6734917
2024-12-26  1206.133911  1217.188348  1203.853555  1213.767935  10016178
2024-12-27  1210.595459  1217.386785  1206.580087  1207.869004   7000397
2024-12-30  1200.333984  1212.726960  1197.756270  1205.985254   8818766

In [20]:
stock.to_csv("../data/reliance_cleaned.csv")